// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHXJFMTC2Ayu7a2ptvCLifL6z1101TKYA',
    appId: '1:457228441333:web:4aec4e4ac139d6664257bc',
    messagingSenderId: '457228441333',
    projectId: 'testing-44e7c',
    authDomain: 'testing-44e7c.firebaseapp.com',
    storageBucket: 'testing-44e7c.firebasestorage.app',
    measurementId: 'G-LXD3QMZ7VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAfOLx9K2799ZfkC7OM4ipjOZOTHePCzI',
    appId: '1:457228441333:android:6ca7bc7a131437c84257bc',
    messagingSenderId: '457228441333',
    projectId: 'testing-44e7c',
    storageBucket: 'testing-44e7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7m4vHyfC7ByjnSK-Bc0zl3M4Qvrsevi8',
    appId: '1:457228441333:ios:0ac2681fe947c7484257bc',
    messagingSenderId: '457228441333',
    projectId: 'testing-44e7c',
    storageBucket: 'testing-44e7c.firebasestorage.app',
    iosBundleId: 'com.example.pertroFleet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7m4vHyfC7ByjnSK-Bc0zl3M4Qvrsevi8',
    appId: '1:457228441333:ios:0ac2681fe947c7484257bc',
    messagingSenderId: '457228441333',
    projectId: 'testing-44e7c',
    storageBucket: 'testing-44e7c.firebasestorage.app',
    iosBundleId: 'com.example.pertroFleet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHXJFMTC2Ayu7a2ptvCLifL6z1101TKYA',
    appId: '1:457228441333:web:11ab319bc3093fbd4257bc',
    messagingSenderId: '457228441333',
    projectId: 'testing-44e7c',
    authDomain: 'testing-44e7c.firebaseapp.com',
    storageBucket: 'testing-44e7c.firebasestorage.app',
    measurementId: 'G-655TJREXWZ',
  );
}
